#!/usr/bin/env ruby

require 'optparse'
require_relative '../lib/csvpp'

$options = {}
option_parser = OptionParser.new do |opts|
  opts.on('-f', '--format FORMAT') do |format|
    $options[:format] = format.strip
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

HELP = option_parser.help
option_parser.parse!

format = $options[:format]

json = CSVPP.json(
  input: ARGF.read,
  format: File.read(format)
)

# Forgive me Matz for I have sinned
system %{echo '#{json}' | python -m json.tool}
